_extends: .github

repository:
  name: tigerlilyobservatory.github.io
  description: Tiger Lily Plants blog
  homepage: https://blog.aperiodicity.com

  # A comma-separated list of topics to set on the repository
  topics: blog
  private: false