_extends: .github

repository:
  name: tigerlilyobservatory.github.io
  description: Tiger Lily Plants LLC. primary website
  homepage: https://tiger-lily-plants.com

  # A comma-separated list of topics to set on the repository
  topics: blog, company website
  private: false
