title: Tiger Lily Plants
email: emma.ann.doyle@gmail.com
author: Emma Doyle
description: |+
  The official site of Tiger Lily Plants, a place where I post updates about my personal plant collection and store
baseurl: ""
url: https://store.tiger-lily-plants.com
# bluesky_username: emmeowzing
# github_username:  emmeowzing
# linkedin_username: emmeowzing
source: site/

paginate: 5
paginate_path: /posts/page:num/
google_analytics: G-2PVB8KPX2Z

# Build settings
theme: minima

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-redirect-from
  # - last-modified-at

# https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled:     true
  collections: true

exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - LICENSE
  - CNAME

whitelist:
  - jekyll-redirect-from